services:
  - type: web
    name: api-comentarios
    env: python
    buildCommand: ""
    startCommand: python app.py
    envVars:
      - key: FLASK_ENV
        value: production
    plan: free
    autoDeploy: true
